### ISSUE TITLE
Suggest : Add docker environment

### ISSUE THREAD

**Issue by Jayllyz** [YungBricoCoop/statsfm-card#1]
A docker compose would be useful for development and self-hosting on a system without php.

**Comment by YungBricoCoop** [comment]
Ok it's done ! (70bbd87)
I made a very simple docker setup, don't hesitate to suggest other modifications or simply make a pull request. 

And thanks for using it on your GitHub profile :thumbsup:

**Comment by Jayllyz** [comment]
<img width="1502" alt="image" src="https://github.com/YungBricoCoop/statsfm-card/assets/16305216/bd632e11-2e35-41ce-9a6d-ddcdb0c029e9">

There seems to be a problem with dependencies or did I miss something?

To reproduce :

```bash
docker compose up -d
docker exec -it <id> composer install 
```

then <http://localhost:80/username?=name>

**Comment by YungBricoCoop** [comment]
Thanks for the stacktrace, I just updated the code for image generation and modified the dockerfile so that PHP runs on Apache. Normally everything should work fine (a3b0754)

**Comment by Jayllyz** [comment]
It works, thank you!
